export const TASK_TYPES = [
  { value: 'Drafting',             label: 'Drafting' },
  { value: 'Review',               label: 'Review' },
  { value: 'Approval',             label: 'Approval' },
  { value: 'Signing',              label: 'Signing' },
  { value: 'Negotiation',          label: 'Negotiation' },
  { value: 'Other',                label: 'Other' },
  { value: 'ASSIGN_REQUEST',       label: 'Assign Request' },
  { value: 'INTAKE_REVIEW',        label: 'Intake Review' },
  { value: 'LEGAL_REVIEW',         label: 'Legal Review' },
  { value: 'DRAFT_DOCUMENT',       label: 'Draft Document' },
  { value: 'MANAGER_APPROVAL',     label: 'Manager Approval' },
  { value: 'REQUEST_REVISIONS',    label: 'Request Revisions' },
  { value: 'BUSINESS_INPUT',       label: 'Business Input' },
  { value: 'UPLOAD_DOCUMENT',      label: 'Upload Document' },
  { value: 'PREPARE_FOR_SIGNATURE','label': 'Prepare for Signature' },
  { value: 'SEND_SIGNATURE_EMAIL', label: 'Send Signature Email' },
  { value: 'FOLLOW_UP_SIGNATURE',  label: 'Follow Up on Signature' },
  { value: 'STORE_SIGNED_DOCUMENT',label: 'Store Signed Document' },
  { value: 'CLOSE_REQUEST',        label: 'Close Request' },
  { value: 'RESOLVE_COMMENT',      label: 'Resolve Comment' },
  { value: 'GENERAL_TASK',         label: 'General Task' },
];
